"""Add columns to appointment table

Revision ID: 0cc4804d0829
Revises: 
Create Date: 2025-04-24 19:32:33.401595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc4804d0829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_inpatient', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nurse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appointment_nurse_id', 'nurse', ['nurse_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_room_id', 'room', ['room_id'], ['id'])

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medication_charges', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('admission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_bill_appointment_id', 'appointment', ['appointment_id'], ['id'])
        batch_op.drop_column('medicine_charges')

    with op.batch_alter_table('prescription_medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dispensed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dispensed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('room_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('prescription_medication', schema=None) as batch_op:
        batch_op.drop_column('dispensed_at')
        batch_op.drop_column('dispensed')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicine_charges', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('fk_bill_appointment_id', type_='foreignkey')
        batch_op.alter_column('admission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('payment_date')
        batch_op.drop_column('medication_charges')
        batch_op.drop_column('appointment_id')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointment_room_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_nurse_id', type_='foreignkey')
        batch_op.drop_column('nurse_id')
        batch_op.drop_column('room_id')
        batch_op.drop_column('is_inpatient')

    with op.batch_alter_table('admission', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
